//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// VHMOFInsp.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VHMOFINSP_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDB_BMP_USER                    130
#define IDB_BMP_MODEL_CHANGE            131
#define IDB_BMP_MODEL_INFO              132
#define IDB_BMP_TEST                    133
#define IDB_BMP_MAINT                   134
#define IDB_BMP_SYSTEM                  135
#define IDB_BMP_INITIAL                 136
#define IDB_BMP_FIRMWARE                137
#define IDB_BMP_EXIT                    138
#define IDD_USERID                      139
#define IDD_MESSAGE_ERROR               141
#define IDB_BITMAP_USERID               143
#define IDI_ICON_CONFIRM                144
#define IDI_ICON_ENABLE                 145
#define IDI_ICON_DISABLE                146
#define IDD_MODEL_INFO                  147
#define IDD_MODEL_INFO_FUSING           149
#define IDD_MODEL_INFO_DATA             151
#define IDD_MODEL_CHANGE                153
#define IDD_INITIALIZE                  157
#define IDD_TEST_READY                  159
#define IDD_TEST_PATTERN                161
#define IDD_SYSTEM                      163
#define IDD_PASSWORD                    166
#define IDB_BMP_PASSWORD                168
#define IDD_MAINTENANCE                 169
#define IDD_AUTO_FIRMWARE               171
#define IDD_MESSAGE_QUESTION            174
#define IDC_BTN_MA_USERID               1000
#define IDC_BTN_MA_MODEL_CHANGE         1001
#define IDC_STT_USER_ID_TITLE           1001
#define IDC_BTN_MA_MODEL_INFO           1002
#define IDC_BTN_UI_CONFIRM              1002
#define IDC_BTN_MA_TEST                 1003
#define IDC_BTN_UI_CANCEL               1003
#define IDC_BTN_MA_MAINT                1004
#define IDC_STT_UI_USER_ID_TIT          1004
#define IDC_BTN_MA_SYSTEM               1005
#define IDC_EDT_UI_USER_ID              1005
#define IDC_BTN_MA_INITIAL              1006
#define IDC_PIC_UI_IMAGE                1006
#define IDC_BTN_MA_FIRMWARE             1007
#define IDC_EDT_ERR_MESSAGE             1007
#define IDC_BTN_MA_EXIT                 1008
#define IDC_STT_ERR_TITLE               1008
#define IDC_BTN_ERR_CLOSE               1009
#define IDC_STT_MAIN_MLOG_VIEW          1010
#define IDC_STT_MI_MODEL_NAME           1011
#define IDC_STT_MI_MODEL_NAME_VALUE     1012
#define IDC_STT_MI_SAVE_MODEL           1013
#define IDC_EDT_MI_SAVE_MODEL           1014
#define IDC_TAB_MI_MODEL_INFO           1015
#define IDC_BTN_MI_SAVE_EXIT            1016
#define IDC_BTN_MI_CANCEL               1017
#define IDC_STT_MF_POWER_SEQ_TITLE      1017
#define IDC_STT_MF_POWER_INFO_TITLE     1018
#define IDC_BTN_MI_FUSING               1018
#define IDC_STT_MF_POWER_LIMIT_TITLE    1019
#define IDC_EDT_MF_VCC                  1020
#define IDC_EDT_MF_VCC_OFFSET           1021
#define IDC_EDT_MF_VEL                  1022
#define IDC_EDT_MF_VEL_OFFSET           1023
#define IDC_EDT_MF_LIMIT_VCC_LOW        1024
#define IDC_EDT_MF_LIMIT_VCC_HIGH       1025
#define IDC_EDT_MF_LIMIT_VEL_LOW        1026
#define IDC_EDT_MF_LIMIT_VEL_HIGH       1027
#define IDC_EDT_MF_LIMIT_ICC_LOW        1028
#define IDC_EDT_MF_LIMIT_ICC_HIGH       1029
#define IDC_EDT_MF_LIMIT_IEL_LOW        1030
#define IDC_EDT_MF_LIMIT_IEL_HIGH       1031
#define IDC_CMB_MF_PWR_ON_SEQ_1         1032
#define IDC_CMB_MF_PWR_ON_DELAY_1       1033
#define IDC_CMB_MF_PWR_ON_SEQ_2         1034
#define IDC_CMB_MF_PWR_ON_SEQ_3         1035
#define IDC_CMB_MF_PWR_ON_SEQ_4         1036
#define IDC_CMB_MF_PWR_ON_SEQ_5         1037
#define IDC_CMB_MF_PWR_ON_SEQ_6         1038
#define IDC_CMB_MF_PWR_ON_DELAY_2       1039
#define IDC_CMB_MF_PWR_ON_DELAY_3       1040
#define IDC_CMB_MF_PWR_ON_DELAY_4       1041
#define IDC_CMB_MF_PWR_ON_DELAY_5       1042
#define IDC_CMB_MF_PWR_OFF_SEQ_1        1043
#define IDC_CMB_MF_PWR_OFF_DELAY_1      1044
#define IDC_CMB_MF_PWR_OFF_SEQ_2        1045
#define IDC_CMB_MF_PWR_OFF_SEQ_3        1046
#define IDC_CMB_MF_PWR_OFF_SEQ_4        1047
#define IDC_CMB_MF_PWR_OFF_SEQ_5        1048
#define IDC_CMB_MF_PWR_OFF_SEQ_6        1049
#define IDC_CMB_MF_PWR_OFF_DELAY_2      1050
#define IDC_CMB_MF_PWR_OFF_DELAY_3      1051
#define IDC_CMB_MF_PWR_OFF_DELAY_4      1052
#define IDC_CMB_MF_PWR_OFF_DELAY_5      1053
#define IDC_BTN_MF_FUSING               1054
#define IDC_CMB_MF_PWR_ON_DELAY_6       1054
#define IDC_STT_MF_SIGNAL_INFO_TITLE    1055
#define IDC_STT_MD_INTERFACE_TITLE      1055
#define IDC_STT_MF_TIMING_TITLE         1056
#define IDC_STT_MD_PATTERN_TITLE        1056
#define IDC_CMB_MF_SIGNAL_PIXEL         1057
#define IDC_CMB_MD_I2C_PULL_UP          1057
#define IDC_CMB_MF_SIGNAL_BIT           1058
#define IDC_CMB_MD_I2C_LEVEL            1058
#define IDC_CMB_MF_SIGNAL_ROTATE        1059
#define IDC_CMB_MD_I2C_CLOCK            1059
#define IDC_EDT_SY_EQP_NAME             1059
#define IDC_CMB_MF_SIGNAL_TYPE          1060
#define IDC_CMB_MD_PTN_NAME             1060
#define IDC_CMB_MF_SIGNAL_FRS_MODE      1061
#define IDC_CMB_MD_SPI_PULL_UP          1061
#define IDC_CMB_MF_SIGNAL_BIT_SELECT    1062
#define IDC_CMB_MD_SPI_LEVEL            1062
#define IDC_CBO_SY_EAS_USE              1062
#define IDC_EDT_MF_TIMING_FREQ          1063
#define IDC_CMB_MD_SPI_CLOCK            1063
#define IDC_EDT_MF_TIMING_VSYNC         1064
#define IDC_EDT_MD_PTN_VCC              1064
#define IDC_EDT_MF_TIMING_HOR_TOTAL     1065
#define IDC_CMB_MD_GPIO_LEVEL           1065
#define IDC_EDT_MF_TIMING_HOR_ACTIVE    1066
#define IDC_EDT_MD_PTN_VEL              1066
#define IDC_EDT_SY_MES_SERVICEPORT      1066
#define IDC_EDT_MF_TIMING_HOR_WIDTH     1067
#define IDC_EDT_MD_PTN_ICC              1067
#define IDC_EDT_SY_MES_NETWORK          1067
#define IDC_EDT_MF_TIMING_HOR_BP        1068
#define IDC_EDT_MD_PTN_IEL              1068
#define IDC_EDT_SY_MES_DEMONPORT        1068
#define IDC_EDT_MF_TIMING_HOR_FP        1069
#define IDC_EDT_MD_PTN_LOCK_TIME        1069
#define IDC_EDT_SY_MES_LOCALSUBJECT     1069
#define IDC_EDT_MF_TIMING_VER_TOTAL     1070
#define IDC_EDT_MD_PTN_MAX_TIME         1070
#define IDC_EDT_SY_MES_REMOTESUBJECT    1070
#define IDC_EDT_MF_TIMING_VER_ACTIVE    1071
#define IDC_EDT_MD_PTN_VSYNC            1071
#define IDC_EDT_SY_EAS_SERVICEPORT      1071
#define IDC_EDT_MF_TIMING_VER_WIDTH     1072
#define IDC_CMB_MD_PTN_ONOFF            1072
#define IDC_EDT_SY_EAS_NETWORK          1072
#define IDC_EDT_MF_TIMING_VER_BP        1073
#define IDC_LST_MD_PTN_LIST             1073
#define IDC_EDT_SY_EAS_DEMONPORT        1073
#define IDC_EDT_MF_TIMING_VER_FP        1074
#define IDC_BTN_MD_PTN_ADD              1074
#define IDC_EDT_SY_EAS_LOCALSUBJECT     1074
#define IDC_LST_MC_MODEL_LIST           1075
#define IDC_EDT_MF_SIGNAL_CLOCK_DELAY   1075
#define IDC_BTN_MD_PTN_MODIFY           1075
#define IDC_EDT_SY_EAS_REMOTESUBJECT    1075
#define IDC_BTN_LOAD                    1076
#define IDC_BTN_MC_LOAD                 1076
#define IDC_CMB_MF_PWR_OFF_DELAY_6      1076
#define IDC_BTN_MD_PTN_DEL              1076
#define IDC_BTN_MD_PTN_UP               1077
#define IDC_EDT_MF_VDD                  1077
#define IDC_BTN_MD_PTN_DOWN             1078
#define IDC_EDT_MF_VDD_OFFSET           1078
#define IDC_PIC_MD_PTN_PREVIEW          1079
#define IDC_EDT_MF_LIMIT_VDD_LOW        1079
#define IDC_STT_PTN_NO                  1080
#define IDC_EDT_MF_LIMIT_VDD_HIGH       1080
#define IDC_BTN_MD_PTN_APPLY_ALL        1081
#define IDC_STT_MI_FUSING_PG1           1081
#define IDC_EDT_MF_LIMIT_IDD_LOW        1081
#define IDC_CMB_MD_GPIO_PULL_UP         1082
#define IDC_STT_INI_TITLE               1082
#define IDC_STT_MI_FUSING_PG2           1082
#define IDC_EDT_MF_LIMIT_IDD_HIGH       1082
#define IDC_STT_INI_FILE_SYSTEM         1083
#define IDC_STT_MD_PWM_SET_TITLE        1083
#define IDC_CMB_MF_INIT_SCRIPT          1083
#define IDC_STT_INI_FILE_MODEL          1084
#define IDC_EDT_MF_LIMIT_IDD_LOW2       1084
#define IDC_CMB_MC_MODEL_INCH           1085
#define IDC_STT_INI_FILE_PATTERN        1085
#define IDC_EDT_MF_LIMIT_IDD_LOW3       1085
#define IDC_STT_INI_FILE_TITLE          1086
#define IDC_CMB_MD_SPI_LEVEL2           1086
#define IDC_STT_INI_CONN_TITLE          1087
#define IDC_STT_INI_CONN_PG1            1088
#define IDC_STT_INI_CONN_QSPI           1089
#define IDC_STT_INI_CONN_DIO            1090
#define IDC_STT_INI_CONN_MELSEC         1091
#define IDC_BTN_INI_RETRY               1092
#define IDC_BTN_INI_RETRY2              1093
#define IDC_BTN_INI_CANCEL              1093
#define IDC_STT_TR_TITLE                1093
#define IDC_STT_INI_CONN_PG2            1094
#define IDC_STT_TR_PID_TITLE            1094
#define IDC_STT_TR_PID_VALUE            1095
#define IDC_STT_TR_QTY_TOTAL_TITLE      1096
#define IDC_STT_TR_QTY_OK_TITLE         1097
#define IDC_STT_TR_QTY_NG_TITLE         1098
#define IDC_BTN_SY_MODEL_FILE_PATH      1098
#define IDC_STT_TR_QTY_TOTAL_VALUE      1099
#define IDC_BTN_SY_PATTERN_FILE_PATH    1099
#define IDC_STT_TR_QTY_OK_VALUE         1100
#define IDC_BTN_SY_EDID_FILE_PATH       1100
#define IDC_STT_TR_QTY_NG_VALUE         1101
#define IDC_STT_TR_QTY_RESET            1102
#define IDC_STT_TR_STATUS_MSG           1103
#define IDC_BTN_TR_TEST_START           1104
#define IDC_STT_TP_PATTERN_LIST_TITLE   1105
#define IDC_LST_TP_PATTERN_LIST         1106
#define IDC_STT_TP_MEAS_VCC_TITLE       1107
#define IDC_STT_EQP_NAME_VALUE          1108
#define IDC_STT_TP_MEAS_VCC_VALUE       1108
#define IDC_STT_OP_MODE_VALUE           1109
#define IDC_STT_TP_MEAS_VEL_TITLE       1109
#define IDC_STT_USER_ID_VALUE           1110
#define IDC_STT_TP_MEAS_VEL_VALUE       1110
#define IDC_STT_USER_NAME_VALUE         1111
#define IDC_STT_TP_MEAS_ICC_TITLE       1111
#define IDC_STT_MODEL_NAME_VALUE        1112
#define IDC_STT_TP_MEAS_ICC_VALUE       1112
#define IDC_STT_RESOLUTION_VALUE        1113
#define IDC_STT_TP_MEAS_IEL_TITLE       1113
#define IDC_STT_SIGNALBIT_VALUE         1114
#define IDC_STT_TP_MEAS_IEL_VALUE       1114
#define IDC_STT_VCC_VALUE               1115
#define IDC_STT_TP_GRAY_LEVEL_R_TITLE   1115
#define IDC_STT_VDD_VALUE               1116
#define IDC_STT_TP_GRAY_LEVEL_R_VALUE   1116
#define IDC_STT_TP_GRAY_LEVEL_G_TITLE   1117
#define IDC_STT_VEL_VALUE               1117
#define IDC_STT_TP_GRAY_LEVEL_G_VALUE   1118
#define IDC_STT_STATION_INFO_TIT        1119
#define IDC_STT_TP_GRAY_LEVEL_B_TITLE   1119
#define IDC_STT_MODEL_INFO_TIT          1120
#define IDC_STT_TP_GRAY_LEVEL_B_VALUE   1120
#define IDC_STT_EQP_NAME_TIT            1121
#define IDC_STT_TP_MEAS_IDD_TITLE       1121
#define IDC_STT_OP_MODE_TIT             1122
#define IDC_STT_TP_MEAS_IDD_VALUE       1122
#define IDC_STT_USER_ID_TIT             1123
#define IDC_STT_TP_TACT_TIME_VALUE      1123
#define IDC_STT_USER_NAME_TIT           1124
#define IDC_STT_TP_MEAS_VDD_TITLE       1124
#define IDC_STT_MODEL_NAME_TIT          1125
#define IDC_STT_TP_EVENT_MSG_TITLE      1125
#define IDC_STT_RESOLUTION_TIT          1126
#define IDC_LST_TP_EVENT_MSG            1126
#define IDC_STT_SIGNALBIT_TIT           1127
#define IDC_BTN_SY_SAVE_EXIT            1127
#define IDC_STT_TP_MEAS_VDD_VALUE       1127
#define IDC_STT_VOLT_TIT                1128
#define IDC_BTN_SY_CANCEL               1128
#define IDC_STT_PW_TITLE                1129
#define IDC_STT_VCC_TIT                 1130
#define IDC_EDT_PW_PASSWORD             1130
#define IDC_STT_VDD_TIT                 1131
#define IDC_BTN_PW_CONFIRM              1131
#define IDC_STT_VGH_TIT                 1132
#define IDC_STT_VEL_TIT                 1132
#define IDC_BTN_PW_CLOSE                1132
#define IDC_STT_VGL_TIT                 1133
#define IDC_PIC_PW_IMAGE                1133
#define IDC_STT_VGH_VALUE               1134
#define IDC_BTN_MT_CLOSE                1134
#define IDC_STT_VGL_VALUE               1135
#define IDC_STT_AF_TITLE                1135
#define IDC_STT_VBL_TIT                 1136
#define IDC_STT_AF_FILE_PATH            1136
#define IDC_STT_VBL_VALUE               1137
#define IDC_EDT_AF_FILE_PATH            1137
#define IDC_STT_FW_VERSION_TIT          1138
#define IDC_BTN_AF_FILE_OPEN            1138
#define IDC_STT_MAIN_APP_TIT            1139
#define IDC_STT_AF_READ_VERSION         1139
#define IDC_STT_MAIN_APP_VALUE          1140
#define IDC_EDT_AF_READ_VERSION         1140
#define IDC_STT_MAIN_FPGA_TIT           1141
#define IDC_BTN_AF_READ_VERSION         1141
#define IDC_STT_MAIN_FPGA_VALUE         1142
#define IDC_STT_MC_TITLE                1142
#define IDC_BTN_AF_DOWNLOAD_START       1142
#define IDC_PROG_AF_PROGRESS            1143
#define IDC_STT_AF_PROGRESS             1144
#define IDC_STT_DP_FPGA_TIT             1145
#define IDC_STT_SY_SYSTEM_TITLE         1145
#define IDC_STT_AF_PERCENT              1145
#define IDC_STT_DP_FPGA_VALUE           1146
#define IDC_BTN_AF_CLOSE                1146
#define IDC_STT_AF_STATUS               1147
#define IDC_STT_AF_CH_SELECT            1148
#define IDC_CMB_AF_CH_SELECT            1149
#define IDC_STT_MQ_MESSAGE              1150
#define IDC_BTN_MQ_CONFIRM              1151
#define IDC_BTN_MQ_CANCEL               1152
#define IDC_STT_SY_STATION_TIT          1156
#define IDC_STT_SY_MES_TIT              1158
#define IDC_IPD_SY_MES_LOCAL_IP         1159
#define IDC_STT_SY_PATH_TIT             1160
#define IDC_EDT_SY_MODEL_FILE_PATH      1161
#define IDC_EDT_SY_PATTERN_FILE_PATH    1162
#define IDC_EDT_SY_EDID_FILE_PATH       1163
#define IDC_STT_SY_EAS_TIT              1165
#define IDC_STT_MC_MODEL_INCH_TITLE     1230
#define IDC_BTN_MC_ALL_MODEL            1231
#define IDC_STT_MC_DRIVE_PATH           1232
#define IDC_STT_MC_MODEL_LIST_TITLE     1233
#define IDC_STT_MC_INCH                 1234

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
