//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// VHMOFInsp.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VHMOFINSP_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDB_BMP_USER                    130
#define IDB_BMP_MODEL_CHANGE            131
#define IDB_BMP_MODEL_INFO              132
#define IDB_BMP_TEST                    133
#define IDB_BMP_MAINT                   134
#define IDB_BMP_SYSTEM                  135
#define IDB_BMP_INITIAL                 136
#define IDB_BMP_FIRMWARE                137
#define IDB_BMP_EXIT                    138
#define IDD_USERID                      139
#define IDD_MESSAGE_ERROR               141
#define IDB_BITMAP_USERID               143
#define IDI_ICON_CONFIRM                144
#define IDI_ICON_ENABLE                 145
#define IDI_ICON_DISABLE                146
#define IDD_MODEL_INFO                  147
#define IDD_MODEL_INFO_FUSING           149
#define IDD_MODEL_INFO_DATA             151
#define IDD_MODEL_CHANGE                153
#define IDD_INITIALIZE                  157
#define IDD_TEST_READY                  159
#define IDD_TEST_PATTERN                161
#define IDD_SYSTEM                      163
#define IDD_PASSWORD                    166
#define IDB_BMP_PASSWORD                168
#define IDD_MAINTENANCE                 169
#define IDD_AUTO_FIRMWARE               171
#define IDD_MESSAGE_QUESTION            174
#define IDD_MAINTENANCE_PG              176
#define IDD_MAINTENANCE_DIO             178
#define IDD_PANELID                     180
#define IDD_DEFECT_RESULT               182
#define IDD_SAFETY_LOCK                 184
#define IDD_SENSOR_VIEW                 187
#define IDB_BMP_ERROR_LIST              189
#define IDD_ERROR_LIST                  190
#define IDC_BTN_MA_USERID               1000
#define IDC_BTN_MA_MODEL_CHANGE         1001
#define IDC_STT_USER_ID_TITLE           1001
#define IDC_BTN_MA_MODEL_INFO           1002
#define IDC_BTN_UI_CONFIRM              1002
#define IDC_BTN_MA_TEST                 1003
#define IDC_BTN_UI_CANCEL               1003
#define IDC_BTN_MA_MAINT                1004
#define IDC_STT_UI_USER_ID_TIT          1004
#define IDC_BTN_MA_SYSTEM               1005
#define IDC_EDT_UI_USER_ID              1005
#define IDC_BTN_MA_INITIAL              1006
#define IDC_PIC_UI_IMAGE                1006
#define IDC_BTN_MA_FIRMWARE             1007
#define IDC_EDT_ERR_MESSAGE             1007
#define IDC_BTN_MA_EXIT                 1008
#define IDC_STT_ERR_TITLE               1008
#define IDC_BTN_ERR_CLOSE               1009
#define IDC_BTN_MA_ERROR_LIST           1009
#define IDC_STT_MAIN_MLOG_VIEW          1010
#define IDC_STT_MI_MODEL_NAME           1011
#define IDC_STT_MI_MODEL_NAME_VALUE     1012
#define IDC_STT_MI_SAVE_MODEL           1013
#define IDC_EDT_MI_SAVE_MODEL           1014
#define IDC_TAB_MI_MODEL_INFO           1015
#define IDC_BTN_MI_SAVE_EXIT            1016
#define IDC_BTN_MI_CANCEL               1017
#define IDC_STT_MF_POWER_SEQ_TITLE      1017
#define IDC_LST_EL_ERRORLIST_VIEW       1017
#define IDC_STT_MF_POWER_INFO_TITLE     1018
#define IDC_BTN_MI_FUSING               1018
#define IDC_STT_MF_POWER_LIMIT_TITLE    1019
#define IDC_EDT_MF_VCC                  1020
#define IDC_EDT_MF_VCC_OFFSET           1021
#define IDC_EDT_MF_VEL                  1022
#define IDC_EDT_MF_VEL_OFFSET           1023
#define IDC_EDT_MF_LIMIT_VCC_LOW        1024
#define IDC_EDT_MF_LIMIT_VCC_HIGH       1025
#define IDC_EDT_MF_LIMIT_VEL_LOW        1026
#define IDC_EDT_MF_LIMIT_VEL_HIGH       1027
#define IDC_EDT_MF_LIMIT_ICC_LOW        1028
#define IDC_EDT_MF_LIMIT_ICC_HIGH       1029
#define IDC_EDT_MF_LIMIT_IEL_LOW        1030
#define IDC_EDT_MF_LIMIT_IEL_HIGH       1031
#define IDC_CMB_MF_PWR_ON_SEQ_1         1032
#define IDC_CMB_MF_PWR_ON_DELAY_1       1033
#define IDC_CMB_MF_PWR_ON_SEQ_2         1034
#define IDC_EDT_SL_PASSWORD             1034
#define IDC_CMB_MF_PWR_ON_SEQ_3         1035
#define IDC_CMB_MF_PWR_ON_SEQ_4         1036
#define IDC_CMB_MF_PWR_ON_SEQ_5         1037
#define IDC_CMB_MF_PWR_ON_SEQ_6         1038
#define IDC_CMB_MF_PWR_ON_DELAY_2       1039
#define IDC_CMB_MF_PWR_ON_DELAY_3       1040
#define IDC_CMB_MF_PWR_ON_DELAY_4       1041
#define IDC_CMB_MF_PWR_ON_DELAY_5       1042
#define IDC_CMB_MF_PWR_OFF_SEQ_1        1043
#define IDC_CMB_MF_PWR_OFF_DELAY_1      1044
#define IDC_CMB_MF_PWR_OFF_SEQ_2        1045
#define IDC_CMB_MF_PWR_OFF_SEQ_3        1046
#define IDC_CMB_MF_PWR_OFF_SEQ_4        1047
#define IDC_CMB_MF_PWR_OFF_SEQ_5        1048
#define IDC_CMB_MF_PWR_OFF_SEQ_6        1049
#define IDC_CMB_MF_PWR_OFF_DELAY_2      1050
#define IDC_CMB_MF_PWR_OFF_DELAY_3      1051
#define IDC_CMB_MF_PWR_OFF_DELAY_4      1052
#define IDC_CMB_MF_PWR_OFF_DELAY_5      1053
#define IDC_BTN_MF_FUSING               1054
#define IDC_CMB_MF_PWR_ON_DELAY_6       1054
#define IDC_STT_MF_SIGNAL_INFO_TITLE    1055
#define IDC_STT_MD_INTERFACE_TITLE      1055
#define IDC_STT_MF_TIMING_TITLE         1056
#define IDC_STT_MD_PATTERN_TITLE        1056
#define IDC_CMB_MF_SIGNAL_PIXEL         1057
#define IDC_CMB_MD_I2C_PULL_UP          1057
#define IDC_CMB_MF_SIGNAL_BIT           1058
#define IDC_CMB_MD_I2C_LEVEL            1058
#define IDC_CMB_MF_SIGNAL_ROTATE        1059
#define IDC_CMB_MD_I2C_CLOCK            1059
#define IDC_EDT_SY_EQP_NAME             1059
#define IDC_CMB_MF_SIGNAL_TYPE          1060
#define IDC_CMB_MD_PTN_NAME             1060
#define IDC_EDT_SY_LB_START_ADDR        1060
#define IDC_CMB_MF_SIGNAL_FRS_MODE      1061
#define IDC_CMB_MD_SPI_PULL_UP          1061
#define IDC_EDT_SY_EQP_NAME3            1061
#define IDC_EDT_SY_LW_START_ADDR        1061
#define IDC_CMB_MF_SIGNAL_BIT_SELECT    1062
#define IDC_CMB_MD_SPI_LEVEL            1062
#define IDC_CBO_SY_EAS_USE              1062
#define IDC_EDT_MF_TIMING_FREQ          1063
#define IDC_CMB_MD_SPI_CLOCK            1063
#define IDC_CBO_SY_CARRIER_TYPE         1063
#define IDC_EDT_MF_TIMING_VSYNC         1064
#define IDC_EDT_MD_PTN_VCC              1064
#define IDC_EDT_MF_TIMING_HOR_TOTAL     1065
#define IDC_CMB_MD_GPIO_LEVEL           1065
#define IDC_EDT_MF_TIMING_HOR_ACTIVE    1066
#define IDC_EDT_MD_PTN_VEL              1066
#define IDC_EDT_SY_MES_SERVICEPORT      1066
#define IDC_EDT_MF_TIMING_HOR_WIDTH     1067
#define IDC_EDT_MD_PTN_ICC              1067
#define IDC_EDT_SY_MES_NETWORK          1067
#define IDC_EDT_MF_TIMING_HOR_BP        1068
#define IDC_EDT_MD_PTN_IEL              1068
#define IDC_EDT_SY_MES_DEMONPORT        1068
#define IDC_EDT_MF_TIMING_HOR_FP        1069
#define IDC_EDT_MD_PTN_LOCK_TIME        1069
#define IDC_EDT_SY_MES_LOCALSUBJECT     1069
#define IDC_EDT_MF_TIMING_VER_TOTAL     1070
#define IDC_EDT_MD_PTN_MAX_TIME         1070
#define IDC_EDT_SY_MES_REMOTESUBJECT    1070
#define IDC_EDT_MF_TIMING_VER_ACTIVE    1071
#define IDC_EDT_MD_PTN_VSYNC            1071
#define IDC_EDT_SY_EAS_SERVICEPORT      1071
#define IDC_EDT_MF_TIMING_VER_WIDTH     1072
#define IDC_CMB_MD_PTN_ONOFF            1072
#define IDC_EDT_SY_EAS_NETWORK          1072
#define IDC_EDT_MF_TIMING_VER_BP        1073
#define IDC_LST_MD_PTN_LIST             1073
#define IDC_EDT_SY_EAS_DEMONPORT        1073
#define IDC_EDT_MF_TIMING_VER_FP        1074
#define IDC_BTN_MD_PTN_ADD              1074
#define IDC_EDT_SY_EAS_LOCALSUBJECT     1074
#define IDC_LST_MC_MODEL_LIST           1075
#define IDC_EDT_MF_SIGNAL_CLOCK_DELAY   1075
#define IDC_BTN_MD_PTN_MODIFY           1075
#define IDC_EDT_SY_EAS_REMOTESUBJECT    1075
#define IDC_BTN_LOAD                    1076
#define IDC_BTN_MC_LOAD                 1076
#define IDC_CMB_MF_PWR_OFF_DELAY_6      1076
#define IDC_BTN_MD_PTN_DEL              1076
#define IDC_BTN_MD_PTN_UP               1077
#define IDC_EDT_MF_VDD                  1077
#define IDC_BTN_MD_PTN_DOWN             1078
#define IDC_EDT_MF_VDD_OFFSET           1078
#define IDC_PIC_MD_PTN_PREVIEW          1079
#define IDC_EDT_MF_LIMIT_VDD_LOW        1079
#define IDC_STT_PTN_NO                  1080
#define IDC_EDT_MF_LIMIT_VDD_HIGH       1080
#define IDC_BTN_MD_PTN_APPLY_ALL        1081
#define IDC_STT_MI_FUSING_PG1           1081
#define IDC_EDT_MF_LIMIT_IDD_LOW        1081
#define IDC_CMB_MD_GPIO_PULL_UP         1082
#define IDC_STT_INI_TITLE               1082
#define IDC_STT_MI_FUSING_PG2           1082
#define IDC_EDT_MF_LIMIT_IDD_HIGH       1082
#define IDC_STT_INI_FILE_SYSTEM         1083
#define IDC_STT_MD_PWM_SET_TITLE        1083
#define IDC_CMB_MF_INIT_SCRIPT          1083
#define IDC_STT_INI_FILE_MODEL          1084
#define IDC_EDT_MF_PWM_FREQUENCY        1084
#define IDC_STT_MF_FUNCTION_TITLE       1084
#define IDC_CMB_MC_MODEL_INCH           1085
#define IDC_STT_INI_FILE_PATTERN        1085
#define IDC_EDT_MF_PWM_DUTY             1085
#define IDC_CMB_MF_MAIN_BOARD_LED       1085
#define IDC_STT_INI_FILE_TITLE          1086
#define IDC_CMB_MD_PWM_LEVEL            1086
#define IDC_CMB_MF_PWR_ON_SEQ_7         1086
#define IDC_STT_INI_CONN_TITLE          1087
#define IDC_STT_MD_GPIO_SET_TITLE       1087
#define IDC_CMB_MF_PWR_ON_DELAY_7       1087
#define IDC_STT_INI_CONN_PG1            1088
#define IDC_CMB_MD_GPIO1_OUTPUT         1088
#define IDC_CMB_MF_PWR_ON_SEQ_8         1088
#define IDC_STT_INI_CONN_SPI1           1089
#define IDC_CMB_MD_GPIO2_OUTPUT         1089
#define IDC_CMB_MF_PWR_ON_DELAY_8       1089
#define IDC_STT_INI_CONN_DIO1           1090
#define IDC_CMB_MD_GPIO3_OUTPUT         1090
#define IDC_CMB_MF_PWR_ON_SEQ_9         1090
#define IDC_STT_INI_CONN_MELSEC         1091
#define IDC_CMB_MD_GIO1_SETTING         1091
#define IDC_CMB_MF_PWR_ON_DELAY_9       1091
#define IDC_BTN_INI_RETRY               1092
#define IDC_CMB_MF_PWR_ON_SEQ_10        1092
#define IDC_CMB_MD_JIG_TILTING_CHECK    1092
#define IDC_BTN_INI_RETRY2              1093
#define IDC_BTN_INI_CANCEL              1093
#define IDC_STT_TR_TITLE                1093
#define IDC_CMB_MD_GIO2_SETTING         1093
#define IDC_CMB_MF_PWR_ON_DELAY_10      1093
#define IDC_STT_INI_CONN_PG2            1094
#define IDC_STT_TR_PID_TITLE            1094
#define IDC_CMB_MF_PWR_ON_SEQ_11        1094
#define IDC_STT_TR_PID_VALUE            1095
#define IDC_STT_INI_CONN_DIO2           1095
#define IDC_CMB_MD_GIO3_SETTING         1095
#define IDC_CMB_MF_PWR_ON_DELAY_11      1095
#define IDC_STT_TR_QTY_TOTAL_TITLE      1096
#define IDC_CMB_MD_GIO4_SETTING         1096
#define IDC_CMB_MF_PWR_ON_SEQ_12        1096
#define IDC_STT_INI_CONN_QSPI2          1096
#define IDC_STT_INI_CONN_SPI2           1096
#define IDC_STT_TR_QTY_OK_TITLE         1097
#define IDC_STT_MD_FUNCTION_TITLE       1097
#define IDC_CMB_MF_PWR_ON_DELAY_12      1097
#define IDC_STT_TR_QTY_NG_TITLE         1098
#define IDC_BTN_SY_MODEL_FILE_PATH      1098
#define IDC_CMB_MD_CABLE_OPEN           1098
#define IDC_CMB_MF_PWR_OFF_SEQ_7        1098
#define IDC_STT_TR_QTY_TOTAL_VALUE      1099
#define IDC_BTN_SY_PATTERN_FILE_PATH    1099
#define IDC_CMB_MF_PWR_OFF_DELAY_7      1099
#define IDC_STT_TR_QTY_OK_VALUE         1100
#define IDC_BTN_SY_EDID_FILE_PATH       1100
#define IDC_CMB_MF_PWR_OFF_SEQ_8        1100
#define IDC_STT_TR_QTY_NG_VALUE         1101
#define IDC_CMB_MF_PWR_OFF_DELAY_8      1101
#define IDC_STT_TR_QTY_RESET            1102
#define IDC_CMB_MF_PWR_OFF_SEQ_9        1102
#define IDC_STT_TR_STATUS_MSG           1103
#define IDC_CMB_MF_PWR_OFF_DELAY_9      1103
#define IDC_STT_MA_QTY_CH1_OK           1103
#define IDC_BTN_TR_TEST_START           1104
#define IDC_CMB_MF_PWR_OFF_SEQ_10       1104
#define IDC_STT_MA_QTY_CH1_NG           1104
#define IDC_STT_TP_PATTERN_LIST_TITLE   1105
#define IDC_CMB_MF_PWR_OFF_DELAY_10     1105
#define IDC_STT_MA_QTY_CH1_TOTAL_VAL    1105
#define IDC_LST_TP_PATTERN_LIST         1106
#define IDC_CMB_MF_PWR_OFF_SEQ_11       1106
#define IDC_STT_MA_QTY_CH1_OK_VAL       1106
#define IDC_STT_TP_MEAS_VCC_TITLE       1107
#define IDC_CMB_MF_PWR_OFF_DELAY_11     1107
#define IDC_STT_TR_QTY_NG_VALUE2        1107
#define IDC_STT_MA_QTY_CH1_NG_VAL       1107
#define IDC_STT_EQP_NAME_VALUE          1108
#define IDC_STT_TP_MEAS_VCC_VALUE       1108
#define IDC_CMB_MF_PWR_OFF_SEQ_12       1108
#define IDC_STT_OP_MODE_VALUE           1109
#define IDC_STT_TP_MEAS_VEL_TITLE       1109
#define IDC_CMB_MF_PWR_OFF_DELAY_12     1109
#define IDC_STT_USER_ID_VALUE           1110
#define IDC_STT_TP_MEAS_VEL_VALUE       1110
#define IDC_CMB_MF_PWR_ON_SEQ_13        1110
#define IDC_STT_USER_NAME_VALUE         1111
#define IDC_STT_TP_MEAS_ICC_TITLE       1111
#define IDC_CMB_MF_PWR_ON_DELAY_13      1111
#define IDC_STT_MODEL_NAME_VALUE        1112
#define IDC_STT_TP_MEAS_ICC_VALUE       1112
#define IDC_CMB_MF_PWR_OFF_SEQ_13       1112
#define IDC_STT_RESOLUTION_VALUE        1113
#define IDC_STT_TP_MEAS_IEL_TITLE       1113
#define IDC_CMB_MF_PWR_OFF_DELAY_13     1113
#define IDC_STT_SIGNALBIT_VALUE         1114
#define IDC_STT_TP_MEAS_IEL_VALUE       1114
#define IDC_STT_VCC_VALUE               1115
#define IDC_STT_TP_GRAY_LEVEL_R_TITLE   1115
#define IDC_STT_VDD_VALUE               1116
#define IDC_STT_TP_GRAY_LEVEL_R_VALUE   1116
#define IDC_STT_TP_GRAY_LEVEL_G_TITLE   1117
#define IDC_STT_VEL_VALUE               1117
#define IDC_STT_TP_GRAY_LEVEL_G_VALUE   1118
#define IDC_STT_MA_QTY_CH2_OK           1118
#define IDC_STT_STATION_INFO_TIT        1119
#define IDC_STT_TP_GRAY_LEVEL_B_TITLE   1119
#define IDC_STT_MODEL_INFO_TIT          1120
#define IDC_STT_TP_GRAY_LEVEL_B_VALUE   1120
#define IDC_STT_EQP_NAME_TIT            1121
#define IDC_STT_TP_MEAS_IDD_TITLE       1121
#define IDC_STT_OP_MODE_TIT             1122
#define IDC_STT_TP_MEAS_IDD_VALUE       1122
#define IDC_STT_USER_ID_TIT             1123
#define IDC_STT_TP_TACT_TIME_VALUE      1123
#define IDC_STT_USER_NAME_TIT           1124
#define IDC_STT_TP_MEAS_VDD_TITLE       1124
#define IDC_STT_MODEL_NAME_TIT          1125
#define IDC_STT_TP_EVENT_MSG_TITLE      1125
#define IDC_STT_RESOLUTION_TIT          1126
#define IDC_LST_TP_EVENT_MSG            1126
#define IDC_STT_SIGNALBIT_TIT           1127
#define IDC_BTN_SY_SAVE_EXIT            1127
#define IDC_STT_TP_MEAS_VDD_VALUE       1127
#define IDC_STT_VOLT_TIT                1128
#define IDC_BTN_SY_CANCEL               1128
#define IDC_STT_PW_TITLE                1129
#define IDC_STT_STATION_INFO_TIT2       1129
#define IDC_STT_QUANTITY_INFO_TIT       1129
#define IDC_STT_VCC_TIT                 1130
#define IDC_EDT_PW_PASSWORD             1130
#define IDC_STT_VDD_TIT                 1131
#define IDC_BTN_PW_CONFIRM              1131
#define IDC_STT_VGH_TIT                 1132
#define IDC_STT_VEL_TIT                 1132
#define IDC_BTN_PW_CLOSE                1132
#define IDC_STT_VGL_TIT                 1133
#define IDC_PIC_PW_IMAGE                1133
#define IDC_STT_MA_QTY_CH2_NG           1133
#define IDC_STT_VGH_VALUE               1134
#define IDC_BTN_MT_CLOSE                1134
#define IDC_STT_MA_QTY_CH2_TOTAL_VAL    1134
#define IDC_STT_VGL_VALUE               1135
#define IDC_STT_AF_TITLE                1135
#define IDC_STT_MA_QTY_CH2_OK_VAL       1135
#define IDC_STT_VBL_TIT                 1136
#define IDC_STT_AF_FILE_PATH            1136
#define IDC_STT_MA_QTY_CH2_NG_VAL       1136
#define IDC_STT_VBL_VALUE               1137
#define IDC_EDT_AF_FILE_PATH            1137
#define IDC_STT_SENSOR_INFO_TIT         1137
#define IDC_STT_FW_VERSION_TIT          1138
#define IDC_BTN_AF_FILE_OPEN            1138
#define IDC_STT_MAIN_APP_TIT            1139
#define IDC_STT_AF_READ_VERSION         1139
#define IDC_STT_MAIN_APP_VALUE          1140
#define IDC_EDT_AF_READ_VERSION         1140
#define IDC_STT_POWER_MCU_TIT           1141
#define IDC_BTN_AF_READ_VERSION         1141
#define IDC_STT_POWER_MCU_VALUE         1142
#define IDC_STT_MC_TITLE                1142
#define IDC_BTN_AF_DOWNLOAD_START       1142
#define IDC_PROG_AF_PROGRESS            1143
#define IDC_STT_CONNECT_INFO_TIT        1143
#define IDC_STT_AF_PROGRESS             1144
#define IDC_STT_CONNECT_MES             1144
#define IDC_STT_DP_FPGA_TIT             1145
#define IDC_STT_SY_SYSTEM_TITLE         1145
#define IDC_STT_AF_PERCENT              1145
#define IDC_STT_CONNECT_EAS             1145
#define IDC_STT_DP_FPGA_VALUE           1146
#define IDC_BTN_AF_CLOSE                1146
#define IDC_STT_CONNECT_PG1             1146
#define IDC_STT_AF_STATUS               1147
#define IDC_STT_CONNECT_PG2             1147
#define IDC_STT_AF_CH_SELECT            1148
#define IDC_STT_CONNECT_ECS             1148
#define IDC_CMB_AF_CH_SELECT            1149
#define IDC_STT_CONNECT_SPI1            1149
#define IDC_STT_MQ_MESSAGE              1150
#define IDC_STT_CONNECT_SPI2            1150
#define IDC_STT_AF_TARGET               1150
#define IDC_BTN_MQ_CONFIRM              1151
#define IDC_STT_CONNECT_DIO1            1151
#define IDC_CMB_AF_TARGET               1151
#define IDC_BTN_MQ_CANCEL               1152
#define IDC_TAB_MT_MAINTENANCE          1152
#define IDC_STT_CONNECT_DIO2            1152
#define IDC_LST_MO_DIO1_IN              1153
#define IDC_STT_DIO_CONTROL_TIT         1153
#define IDC_LST_MO_DIO1_OUT             1154
#define IDC_STT_MAIN_SPI_VER_TIT        1154
#define IDC_LST_MO_DIO2_IN              1155
#define IDC_STT_MAIN_SPI_VER_VALUE      1155
#define IDC_STT_SY_STATION_TIT          1156
#define IDC_LST_MO_DIO2_OUT             1156
#define IDC_STT_TACTTIME_INFO_TIT       1156
#define IDC_BTN_MO_WRITE_DIO1           1157
#define IDC_STT_SY_MELSEC_TIT           1157
#define IDC_STT_SY_MES_TIT              1158
#define IDC_BTN_MO_WRITE_DIO2           1158
#define IDC_IPD_SY_MES_LOCAL_IP         1159
#define IDC_LST_MO_DIO1_TITLE           1159
#define IDC_STT_SY_PATH_TIT             1160
#define IDC_LST_MO_DIO2_TITLE           1160
#define IDC_EDT_SY_MODEL_FILE_PATH      1161
#define IDC_STT_PID_TITLE               1161
#define IDC_LST_MO_MANUAL_CONTROL_TITLE 1161
#define IDC_EDT_SY_PATTERN_FILE_PATH    1162
#define IDC_EDT_PID_INPUT               1162
#define IDC_EDT_SY_EDID_FILE_PATH       1163
#define IDC_BTN_PID_CONFIRM             1163
#define IDC_BTN_PID_CANCEL              1164
#define IDC_GRP_MP_POWER                1164
#define IDC_STT_SY_EAS_TIT              1165
#define IDC_GRP_MP_I2C                  1165
#define IDC_BTN_MP_POWER_ON             1166
#define IDC_BTN_MP_POWER_OFF            1167
#define IDC_CMB_MP_PATTERN_LIST         1168
#define IDC_EDT_MP_I2C_DEVICE           1169
#define IDC_EDT_MP_I2C_ADDRESS          1170
#define IDC_EDT_MP_I2C_DATA             1171
#define IDC_BTN_MP_I2C_WRITE            1172
#define IDC_BTN_MP_I2C_READ             1173
#define IDC_STT_MP_I2C_RESULT           1174
#define IDC_GRP_MP_SPI                  1175
#define IDC_CMB_MP_PATTERN_CH           1176
#define IDC_EDT_MP_SPI_ADDRESS          1177
#define IDC_EDT_MP_SPI_DATA1            1178
#define IDC_BTN_MP_SPI_WRITE            1179
#define IDC_BTN_MP_SPI_READ             1180
#define IDC_STT_MP_I2C_RESULT2          1181
#define IDC_EDT_MP_SPI_DATA2            1182
#define IDC_EDT_MP_SPI_DATA3            1183
#define IDC_EDT_MP_SPI_DATA4            1184
#define IDC_EDT_MP_SPI_DATA5            1185
#define IDC_CMB_MP_I2C_CH               1186
#define IDC_CMB_MP_SPI_CH               1187
#define IDC_EDT_MP_MEAS_VCC             1188
#define IDC_EDT_MP_MEAS_VIN             1189
#define IDC_BTN_MI_MODIFY               1189
#define IDC_EDT_MP_MEAS_VSYS            1190
#define IDC_BTN_DIO_CTRL_LED_OFF        1190
#define IDC_EDT_MP_MEAS_ICC             1191
#define IDC_BTN_DIO_CTRL_LED_ON         1191
#define IDC_EDT_MP_MEAS_IIN             1192
#define IDC_STT_MA_QTY_TOTAL_TITLE      1192
#define IDC_EDT_MP_MEAS_ISYS            1193
#define IDC_STT_MA_QTY_CH1_TOTAL        1193
#define IDC_STT_MA_QTY_TOTAL_VALUE      1194
#define IDC_STT_MA_QTY_OK_TITLE         1195
#define IDC_STT_MA_QTY_OK_VALUE         1196
#define IDC_STT_MA_QTY_NG_TITLE         1197
#define IDC_STT_MA_QTY_NG_VALUE         1198
#define IDC_STT_MA_QTY_RESET            1199
#define IDC_STT_MA_QTY_CH2_TOTAL        1200
#define IDC_STT_SL_ALARM_LIST           1200
#define IDC_STT_MA_QTY_RESET_CH1        1201
#define IDC_STT_MA_QTY_RESET_CH2        1202
#define IDC_LST_SV_ERROR_LIST           1202
#define IDC_BTN_SV_EXIT                 1203
#define IDC_BTN_DIO_CTRL_MUTE_ON        1203
#define IDC_STT_SV_LEFT_SAFETY_DOOR     1204
#define IDC_BTN_DIO_CTRL_MUTE_OFF       1204
#define IDC_STT_SV_RIGHT_SAFETY_DOOR    1205
#define IDC_BTN_DIO_CTRL_DOOR_OPEN      1205
#define IDC_STT_SV_IONIZER              1206
#define IDC_STT_SV_EMO                  1207
#define IDC_STT_SV_LIGHT_CURTAIN        1208
#define IDC_STT_SV_FAN_IN               1209
#define IDC_STT_SV_FAN_OUT              1210
#define IDC_STT_SV_TEMPATURE            1211
#define IDC_STT_SV_MAIN_AIR             1212
#define IDC_STT_SV_JIG_AIR              1213
#define IDC_STT_SV_CYLINDER_AIR         1214
#define IDC_STT_SV_ION_AIR              1215
#define IDC_BTN_SV_RESET                1216
#define IDC_BTN_SV_LEFT_DOOR_OPEN       1217
#define IDC_BTN_SV_LEFT_DOOR_OPEN2      1218
#define IDC_BTN_SV_RIGHT_DOOR_OPEN      1218
#define IDC_LST_MA_DIN_LIST_A           1222
#define IDC_LST_MA_DIN_LIST_B           1223
#define IDC_STT_MA_TT_MACHINE_TIT       1224
#define IDC_STT_MA_TT_FRONTDOORUP_TIT   1225
#define IDC_STT_MA_TT_FRONTDOORDOWN_TIT 1226
#define IDC_STT_MA_TT_REARDOORUP_TIT    1227
#define IDC_STT_MA_TT_REARDOORDOWN_TIT  1228
#define IDC_STT_MA_TT_JIGTILTINGUP_TIT  1229
#define IDC_STT_MC_MODEL_INCH_TITLE     1230
#define IDC_STT_MA_TT_JIGTILTINGDOWN_TIT 1230
#define IDC_BTN_MC_ALL_MODEL            1231
#define IDC_STT_MA_TT_MACHINE_VAL       1231
#define IDC_STT_MC_DRIVE_PATH           1232
#define IDC_STT_MA_TT_FRONTDOORUP_VAL   1232
#define IDC_STT_MC_MODEL_LIST_TITLE     1233
#define IDC_STT_MA_TT_FRONTDOORDOWN_VAL 1233
#define IDC_STT_MC_INCH                 1234
#define IDC_STT_MA_TT_REARDOORUP_VAL    1234
#define IDC_STT_MA_TT_REARDOORDOWN_VAL  1235
#define IDC_STT_MA_TT_JIGTILTINGUP_VAL  1236
#define IDC_STT_MA_TT_JIGTILTINGDOWN_VAL 1237
#define IDC_STT_MO_FRONT_DOOR_OPEN      1238
#define IDC_STT_MO_FRONT_DOOR_CLOSE     1239
#define IDC_STT_MO_REAR_DOOR_OPEN       1240
#define IDC_STT_MO_REAR_DOOR_CLOSE      1241
#define IDC_STT_MO_LIGHT_CURTAIN_MUTE_ON 1242
#define IDC_STT_MO_LIGHT_CURTAIN_MUTE_OFF 1243
#define IDC_STT_MO_JIG_TILTING_UP       1244
#define IDC_STT_MO_JIG_TILTING_DOWN     1245
#define IDC_STT_MO_LEFT_SAFETY_DOOR_OPEN 1246
#define IDC_STT_MO_RIGHT_SAFETY_DOOR_OPEN 1247
#define IDC_STT_MO_CLAMP_LOCK_CH1       1248
#define IDC_STT_MO_CLAMP_UNLOCK_CH1     1249
#define IDC_STT_MO_CLAMP_LOCK_CH2       1250
#define IDC_STT_MO_CLAMP_UNLOCK_CH2     1251
#define IDC_CHK_MO_AUTO_CONFIRM         1252
#define IDC_STT_DEF_1_TO_1              1253
#define IDC_STT_MO_FRONT_DOOR_HOLDING_ON 1253
#define IDC_STT_DEF_1_TO_2              1254
#define IDC_STT_MO_FRONT_DOOR_HOLDING_ON2 1254
#define IDC_STT_MO_FRONT_DOOR_HOLDING_OFF 1254
#define IDC_STT_DEF_1_TO_3              1255
#define IDC_STT_DEF_1_TO_4              1256
#define IDC_STT_DEF_1_TO_5              1257
#define IDC_STT_DEF_1_TO_6              1258
#define IDC_STT_DEF_1_TO_7              1259
#define IDC_STT_DEF_1_TO_8              1260
#define IDC_STT_DEF_1_TO_9              1261
#define IDC_STT_DEF_1_TO_10             1262
#define IDC_STT_DEF_2_TO_1              1263
#define IDC_STT_DEF_3_TO_1              1264
#define IDC_STT_DEF_4_TO_1              1265
#define IDC_STT_DEF_5_TO_1              1266
#define IDC_STT_DEF_6_TO_1              1267
#define IDC_STT_DEF_7_TO_1              1268
#define IDC_STT_DEF_8_TO_1              1269
#define IDC_STT_DEF_9_TO_1              1270
#define IDC_STT_DEF_10_TO_1             1271
#define IDC_STT_DEF_2_TO_2              1272
#define IDC_STT_DEF_2_TO_3              1273
#define IDC_STT_DEF_2_TO_4              1274
#define IDC_STT_DEF_2_TO_5              1275
#define IDC_STT_DEF_2_TO_6              1276
#define IDC_STT_DEF_2_TO_7              1277
#define IDC_STT_DEF_2_TO_8              1278
#define IDC_STT_DEF_2_TO_9              1279
#define IDC_STT_DEF_2_TO_10             1280
#define IDC_STT_DEF_3_TO_2              1281
#define IDC_STT_DEF_3_TO_3              1282
#define IDC_STT_DEF_3_TO_4              1283
#define IDC_STT_DEF_3_TO_5              1284
#define IDC_STT_DEF_3_TO_6              1285
#define IDC_STT_DEF_3_TO_7              1286
#define IDC_STT_DEF_3_TO_8              1287
#define IDC_STT_DEF_3_TO_9              1288
#define IDC_STT_DEF_3_TO_10             1289
#define IDC_STT_DEF_4_TO_2              1290
#define IDC_STT_DEF_4_TO_3              1291
#define IDC_STT_DEF_4_TO_4              1292
#define IDC_STT_DEF_4_TO_5              1293
#define IDC_STT_DEF_4_TO_6              1294
#define IDC_STT_DEF_4_TO_7              1295
#define IDC_STT_DEF_4_TO_8              1296
#define IDC_STT_DEF_4_TO_9              1297
#define IDC_STT_DEF_4_TO_10             1298
#define IDC_STT_DEF_5_TO_2              1299
#define IDC_STT_DEF_5_TO_3              1300
#define IDC_STT_DEF_5_TO_4              1301
#define IDC_STT_DEF_5_TO_5              1302
#define IDC_STT_DEF_5_TO_6              1303
#define IDC_STT_DEF_5_TO_7              1304
#define IDC_STT_DEF_5_TO_8              1305
#define IDC_STT_DEF_5_TO_9              1306
#define IDC_STT_DEF_5_TO_10             1307
#define IDC_STT_DEF_6_TO_2              1308
#define IDC_STT_DEF_6_TO_3              1309
#define IDC_STT_DEF_6_TO_4              1310
#define IDC_STT_DEF_6_TO_5              1311
#define IDC_STT_DEF_6_TO_6              1312
#define IDC_STT_DEF_6_TO_7              1313
#define IDC_STT_DEF_6_TO_8              1314
#define IDC_STT_DEF_6_TO_9              1315
#define IDC_STT_DEF_6_TO_10             1316
#define IDC_STT_DEF_7_TO_2              1317
#define IDC_STT_DEF_7_TO_3              1318
#define IDC_STT_DEF_7_TO_4              1319
#define IDC_STT_DEF_7_TO_5              1320
#define IDC_STT_DEF_7_TO_6              1321
#define IDC_STT_DEF_7_TO_7              1322
#define IDC_STT_DEF_7_TO_8              1323
#define IDC_STT_DEF_7_TO_9              1324
#define IDC_STT_DEF_7_TO_10             1325
#define IDC_STT_DEF_8_TO_2              1326
#define IDC_STT_DEF_8_TO_3              1327
#define IDC_STT_DEF_8_TO_4              1328
#define IDC_STT_DEF_8_TO_5              1329
#define IDC_STT_DEF_8_TO_6              1330
#define IDC_STT_DEF_8_TO_7              1331
#define IDC_STT_DEF_8_TO_8              1332
#define IDC_STT_DEF_8_TO_9              1333
#define IDC_STT_DEF_8_TO_10             1334
#define IDC_STT_DEF_9_TO_2              1335
#define IDC_STT_DEF_9_TO_3              1336
#define IDC_STT_DEF_9_TO_4              1337
#define IDC_STT_DEF_9_TO_5              1338
#define IDC_STT_DEF_9_TO_6              1339
#define IDC_STT_DEF_9_TO_7              1340
#define IDC_STT_DEF_9_TO_8              1341
#define IDC_STT_DEF_9_TO_9              1342
#define IDC_STT_DEF_9_TO_10             1343
#define IDC_STT_DEF_10_TO_2             1344
#define IDC_STT_DEF_10_TO_3             1345
#define IDC_STT_DEF_10_TO_4             1346
#define IDC_STT_DEF_10_TO_5             1347
#define IDC_STT_DEF_10_TO_6             1348
#define IDC_STT_DEF_10_TO_7             1349
#define IDC_STT_DEF_10_TO_8             1350
#define IDC_STT_DEF_10_TO_9             1351
#define IDC_STT_DEF_10_TO_10            1352
#define IDC_STT_DEF_DETAIL              1353
#define IDC_BTN_DEF_CONFIRM             1354
#define IDC_BTN_DEF_CANCEL              1355
#define IDC_BTN_DEF_UNDO                1356
#define IDC_CTR_EL_DATETIME             1558
#define IDC_STT_SL_TOP                  1580
#define IDC_STT_SL_FIRST                1581
#define IDC_STT_SL_SECOND               1582
#define IDC_STT_SL_PHONE                1583
#define IDC_STT_SL_BOTTOM1              1584
#define IDC_STT_SL_NAME                 1585
#define IDC_STT_SL_BOTTOM2              1586
#define IDC_BTN_SL_OK                   1587
#define IDC_BTN_SL_SENSOR_VIEW          1588
#define IDC_STT_EL_TITLE                1617
#define IDC_BTN_EL_CLOSE                1618
#define IDC_STT_EL_ERRORLIST_OPE        1619

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
